In [9]:
import numpy as np

In [10]:
# Define the state space
states = ["cola preference", "ice tea preference"]
n_states = len(states)
print('Number of hidden states :',n_states)
# Define the observation space
observations = ["cola", "ice tea","lemonade"]
n_observations = len(observations)
print('Number of observations  :',n_observations)

Number of hidden states : 2
Number of observations  : 3


In [11]:
# Initial state distribution (pi values of state)
state_probability = [1, 0]
print("State probability: ", state_probability)
# State transition probabilities between hidden states
transition_probability = np.array([[0.7, 0.3],
                                   [0.5, 0.5]])
print("\nTransition probability:\n", transition_probability)
# Emission probability of observations
emission_probability= np.array([[0.6, 0.1,0.3],
                                 [0.1, 0.7,0.2]])
print("\nEmission probability:\n", emission_probability)

State probability:  [1, 0]

Transition probability:
 [[0.7 0.3]
 [0.5 0.5]]

Emission probability:
 [[0.6 0.1 0.3]
 [0.1 0.7 0.2]]


In [12]:
# output sequence
cola=0
ice=1
lem=2
op_seq=[lem,ice,cola]
print(op_seq)

[2, 1, 0]


In [13]:
# Trellis-The forward procedure
def forward(state_probability,transition_probability,emission_probability):
    for k in range(3):
        alp_c=0
        alp_i=0
        for j in range(2):
            alp_c+=(state_probability[j]*transition_probability[j][0]*emission_probability[j][op_seq[k]])
            alp_i+=(state_probability[j]*transition_probability[j][1]*emission_probability[j][op_seq[k]])
        state_probability[0]=alp_c
        state_probability[1]=alp_i
    print("Total probability: ",alp_c+alp_i)
forward(state_probability,transition_probability,emission_probability)

Total probability:  0.03149999999999999


In [14]:
# Initial state distribution (pi values of state)
state_probability = [1, 0]
new = [1,1]
# State transition probabilities between hidden states
transition_probability = np.array([[0.7, 0.3],
                                   [0.5, 0.5]])
# Emission probability of observations
emission_probability= np.array([[0.6, 0.1,0.3],
                                 [0.1, 0.7,0.2]])
# Trellis-The backward procedure
def backward(new,transition_probability,emission_probability):
    for k in range(2,-1,-1):
        beta_c=0
        beta_i=0
        for j in range(2):
            beta_c+=(new[j]*transition_probability[0][j]*emission_probability[0][op_seq[k]])
            beta_i+=(new[j]*transition_probability[1][j]*emission_probability[1][op_seq[k]])
        new[0]=beta_c
        new[1]=beta_i
    print("Total probability: ",beta_c*state_probability[0] + beta_i*state_probability[1])
backward(new,transition_probability,emission_probability)

Total probability:  0.0315
