In [1]:
import numpy as np

In [2]:
# Define the state space
states = ["cola preference", "ice tea preference"]
n_states = len(states)
print('Number of hidden states :',n_states)
# Define the observation space
observations = ["cola", "ice tea","lemonade"]
n_observations = len(observations)
print('Number of observations  :',n_observations)

Number of hidden states : 2
Number of observations  : 3


In [3]:
# Initial state distribution (pi values of state)
state_probability = [1, 0]
print("State probability: ", state_probability)
# State transition probabilities between hidden states
transition_probability = np.array([[0.7, 0.3],
                                   [0.5, 0.5]])
print("\nTransition probability:\n", transition_probability)
# Emission probability of observations
emission_probability= np.array([[0.6, 0.1,0.3],
                                 [0.1, 0.7,0.2]])
print("\nEmission probability:\n", emission_probability)

State probability:  [1, 0]

Transition probability:
 [[0.7 0.3]
 [0.5 0.5]]

Emission probability:
 [[0.6 0.1 0.3]
 [0.1 0.7 0.2]]


In [4]:
# output sequence
cola=0
ice=1
lem=2
op_seq=[lem,ice,cola]
print(op_seq)

[2, 1, 0]


In [5]:
# Viterbi algorithm
def viterbi(state_probability,transition_probability,emission_probability):
    for k in range(3):
        del_ip=[]
        del_cp=[]
        for j in range(2):
            del_cp.append((state_probability[j]*transition_probability[j][0]*emission_probability[j][op_seq[k]]))
            del_ip.append((state_probability[j]*transition_probability[j][1]*emission_probability[j][op_seq[k]]))
        state_probability[0]=max(del_cp)
        state_probability[1]=max(del_ip)
    print("Probability: ",max(del_cp+del_ip))
viterbi(state_probability,transition_probability,emission_probability)

Probability:  0.01323
